meta_product_name: "Flextables"
meta_title: "FlexTables - The easy way to plan your Flex Classes"
meta_description: "Optimised for the Lernbüro system, students can organise their flexible classes and keep track of homework. Teachers can upload homework and keep track of attendance."
meta_image: "og_image.jpg"
